export enum MESSAGE_TYPES {
    NORMAL = 1,
    SPY_REPORT,
    BATTLE_REPORT,
    EXPEDITION_REPORT,
    TRANSPORT_REPORT,
    ECONOMY,
    ALLIANCE_NORMAL,
    ALLIANCE_INFO,
    ALLIANCE_BATTLE_REPORT,
    ALLIANCE_SPY_REPORT,
    ALLIANCE_EXPEDITION_REPORT,
    ADMIN,
    SYSTEM,
    OTHER
}